version: '2.1'
services:
  ecoeye-app:
    build: .
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
    environment:
      - PYTHONUNBUFFERED=1
      - APP_BIND=0.0.0.0
      - APP_PORT=5000
    ports:
      - "80:5000"
    volumes:
      - ecoeye-data:/app/data
    restart: unless-stopped

  browser:
    image: bh.cr/balenalabs/browser-aarch64:v2.7.0
    privileged: true
    network_mode: host
    environment:
      - LAUNCH_URL=http://localhost:5000
      - ENABLE_GPU=1
      - CURSOR=1
      - SHOW_CURSOR=1
    restart: unless-stopped

volumes:
  ecoeye-data:
